### ISSUE TITLE
Problem with BIOM files

### ISSUE THREAD

**Issue by eperezv** [wwood/singlem#60]
Hello,

First of all, thanks for coding this great tool!

I am trying to generate a biom file and I am getting this error:
```
(singlem) eduardo@eduardo-PC:$ singlem summarise --input_otu_tables otutable1.tsv otutable2.tsv --biom_prefix combined
12/10/2020 12:53:10 AM INFO: Writing BIOM table combined.S1.1.ribosomal_protein_L2_rplB.biom ..
Traceback (most recent call last):
  File "/home/eduardo/miniconda3/envs/singlem/bin/singlem", line 655, in <module>
    biom_output_prefix = args.biom_prefix)
  File "/home/eduardo/miniconda3/envs/singlem/lib/python3.6/site-packages/singlem/summariser.py", line 293, in write_biom_otu_tables
    df2.as_matrix(),
  File "/home/eduardo/miniconda3/envs/singlem/lib/python3.6/site-packages/pandas/core/generic.py", line 5141, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'as_matrix'
```
Do you have any idea about what's going on?
Thanks

**Comment by wwood** [comment]
Just to check this is the newest version i.e. 0.13.2? I have a memory of fixing that already, but could be wrong.

**Comment by eperezv** [comment]
You are absolutely right. I thought my conda installation was updated.
Thanks! It is solved now.

**Comment by MaryoHg** [comment]
Dear @wwood ,

Was the option `--biom_prefix` deprecated? 

I'm working on the `singlem v0.16` and I couldn't find that option either on [SingleM Docs](https://wwood.github.io/singlem/tools/summarise) or into the `singlem summarise --full-help` options in CLI.

Thanks in advance.
